spring:
  application:
    name: zuul-service

server:
  port: 8500

zuul:
  ignoredServices: '*'  # routes에 정의되지 않은 모든 요청은 무시 함
  sensitive-headers:    # header의 모든 정보를 bypass 함
  routes:
    customer:
      path: /api/v1/customer/**   # 사용자가 입력할 url
      serviceId: CUSTOMER-SERVICE # routing을 처리할 endpoint service
      strip-prefix: true          # path에서 /** 앞의 경로는 제거 후 뒷단 서비스로 요청 함
    order:
      path: /api/v1/java/**      # 사용자가 입력할 url
      serviceId: JAVA-SERVICE    # routing을 처리할 endpoint service
      strip-prefix: true          # path에서 /** 앞의 경로는 제거 후 뒷단 서비스로 요청 함      

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

ribbon:
  ConnectTimeout: 5000    # Client에서 서버로 요청시 서버와의 Connection 맺기 까지의 delay time
  ReadTimeout: 2000       # Connection 맺은 후 response 받기 까지 delay time
